name: EpicGuard
version: '${version}'
main: me.xneox.epicguard.paper.EpicGuardPaper
api-version: 1.13

author: neox
website: https://github.com/xxneox/EpicGuard
description: Bot protection system for Minecraft servers.

commands:
  epicguard:
    description: Main plugin command.
    permission: epicguard.admin
    aliases: [ ab, guard, eg, antibot ]